# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Employee Management CI with Gradle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: "20"
          distribution: "corretto"
          # cache: gradle

      - name: Grant x permission to gradlew
        run: chmod +x gradlew

      - name: Build and Test
        run: ./gradlew clean build --console=plain

      - name: Build Docker Image
        run: ./gradlew bootBuildImage --console=plain

      # - name: Log in to Docker Hub
      #   run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      # - name: Tag Docker image
      #   run: docker tag your-application:latest $DOCKERHUB_USERNAME/your-application:latest

      # - name: Push Docker image
      #   run: docker push $DOCKERHUB_USERNAME/your-application:latest
